---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: authtest-ingress
spec:
  hosts:
    - '*'
  gateways:
    - authtest
  http:
    - route:
        - destination:
            host: authtest